GET {{$dotenv SPEECH_ENDPOINT}}/avatar/batchsyntheses/f93712b2-6bf8-4e7e-b335-5f36b8bd46aa?api-version=2024-04-15-preview HTTP/1.1
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$dotenv SPEECH_KEY}}
